---
- name: Install
  hosts: init-host
  gather_facts: no
  become_user: root
  vars_files:
    - "../group_vars/sysctl.yml"
    - "../group_vars/java.yml"

  roles:
    - role: ../roles/python
    - role: ../roles/system
    - role: ../roles/locale
    - role: ../roles/packages
    - role: ../roles/cetos1-basic
    - role: ../roles/netfpga-packs
    - role: ../roles/java
    - role: ../roles/limits

